// Package contract provides Go bindings and types for the ArbitrageExecutor
// Solidity smart contract.
//
// # What is a smart contract?
//
// A smart contract is a program deployed on the Ethereum blockchain.
// Once deployed, it lives at an address and can be called by anyone.
// Its code is immutable and executes deterministically.
//
// # Why do we need a contract for arbitrage?
//
// Arbitrage involves multiple transactions: buy on DEX A, sell on DEX B.
// If we send two separate transactions:
//   - Tx1: buy on Uniswap
//   - Tx2: sell on SushiSwap
//
// There's a race condition: another bot could step in between Tx1 and Tx2,
// making Tx2 unprofitable. Worse, if Tx2 fails, we've already spent money on Tx1.
//
// The solution: bundle both swaps into ONE transaction via a smart contract.
// The contract is atomic: either both swaps succeed, or neither executes.
// This is the core pattern for on-chain arbitrage.
//
// # Flash Loans
//
// A flash loan allows you to borrow an arbitrary amount of tokens, execute
// arbitrary logic (like arbitrage), and repay the loan – all in one transaction.
// If you don't repay, the entire transaction reverts. Zero counterparty risk.
//
// This means capital requirements are effectively zero for the borrower:
// you borrow $1M, run the arb, keep the profit, repay $1M + fee.
// AAVE charges 0.09% for flash loans.
//
// # ABI and Go bindings
//
// To call a Solidity function from Go:
//  1. Compile the Solidity to ABI (Application Binary Interface)
//  2. Use `abigen` to generate Go structs and call helpers from the ABI
//  3. In your Go code: call `contract.ExecuteArbitrage(auth, params...)`
//
// The bindings generated here are hand-written representations of what
// `abigen` would produce. In a real project, run:
//
//	solc --abi contracts/ArbitrageExecutor.sol -o build/
//	abigen --abi build/ArbitrageExecutor.abi --pkg contract --out internal/contract/bindings.go
package contract

import (
	"context"
	"crypto/ecdsa"
	"encoding/hex"
	"errors"
	"fmt"
	"math/big"
	"strings"

	"github.com/user/go-dex-arbitrage/pkg/types"
)

// ---- Solidity ABI definition ------------------------------------------------

// ArbitrageExecutorABI is the JSON ABI for the ArbitrageExecutor contract.
// This would normally be generated by `solc` and read from a file.
// Hand-written here for educational clarity.
const ArbitrageExecutorABI = `[
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "name": "executeArbitrage",
    "type": "function",
    "inputs": [
      {"name": "tokenIn",     "type": "address"},
      {"name": "tokenOut",    "type": "address"},
      {"name": "amountIn",    "type": "uint256"},
      {"name": "amountOutMin","type": "uint256"},
      {"name": "poolBuy",     "type": "address"},
      {"name": "poolSell",    "type": "address"},
      {"name": "deadline",    "type": "uint256"}
    ],
    "outputs": [{"name": "profit", "type": "uint256"}],
    "stateMutability": "nonpayable"
  },
  {
    "name": "executeFlashLoanArb",
    "type": "function",
    "inputs": [
      {"name": "loanToken",   "type": "address"},
      {"name": "loanAmount",  "type": "uint256"},
      {"name": "tokenOut",    "type": "address"},
      {"name": "amountOutMin","type": "uint256"},
      {"name": "poolBuy",     "type": "address"},
      {"name": "poolSell",    "type": "address"}
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "name": "withdraw",
    "type": "function",
    "inputs": [{"name": "token", "type": "address"}],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
]`

// ---- Transaction types ------------------------------------------------------

// ArbitrageParams bundles everything needed to call executeArbitrage.
type ArbitrageParams struct {
	TokenIn      string   // ERC-20 address of the input token
	TokenOut     string   // ERC-20 address of the intermediate/output token
	AmountIn     *big.Int // raw amount (scaled by token decimals)
	AmountOutMin *big.Int // minimum acceptable output (slippage protection)
	PoolBuy      string   // address of the pool to buy on
	PoolSell     string   // address of the pool to sell on
	Deadline     *big.Int // Unix timestamp: revert if block.timestamp > deadline
}

// FlashLoanParams bundles everything for a flash loan arbitrage.
type FlashLoanParams struct {
	LoanToken    string
	LoanAmount   *big.Int
	TokenOut     string
	AmountOutMin *big.Int
	PoolBuy      string
	PoolSell     string
}

// SignedTx represents a fully signed Ethereum transaction ready to broadcast.
type SignedTx struct {
	Hash    string // keccak256 of the encoded transaction
	RawHex  string // hex-encoded RLP of the signed transaction
	GasLimit uint64
	GasPrice *big.Int
	Nonce   uint64
}

// ---- Transaction builder ----------------------------------------------------

// TxBuilder builds and signs Ethereum transactions.
// In production, use go-ethereum's types.NewTransaction and bind.TransactOpts.
// This implementation is intentionally simplified for educational purposes –
// it shows the *concept* without requiring a full Ethereum node connection.
type TxBuilder struct {
	ChainID    *big.Int
	PrivateKey *ecdsa.PrivateKey // nil in testnet-demo / mock mode
	GasPrice   *big.Int
	GasLimit   uint64
}

// NewTxBuilder creates a TxBuilder for the given chain.
func NewTxBuilder(chainID int64, gasPrice *big.Int, gasLimit uint64) *TxBuilder {
	return &TxBuilder{
		ChainID:  big.NewInt(chainID),
		GasPrice: gasPrice,
		GasLimit: gasLimit,
	}
}

// BuildArbitrageTx constructs (but does not sign) an executeArbitrage call.
//
// In production with go-ethereum this would look like:
//
//	auth, _ := bind.NewKeyedTransactorWithChainID(privateKey, chainID)
//	auth.GasPrice = gasPrice
//	auth.GasLimit = gasLimit
//	tx, err := contract.ExecuteArbitrage(auth, params.TokenIn, ...)
func (b *TxBuilder) BuildArbitrageTx(
	ctx context.Context,
	contractAddr string,
	params ArbitrageParams,
	nonce uint64,
) (*SignedTx, error) {
	if contractAddr == "" {
		return nil, errors.New("contract: contractAddr is empty")
	}
	if params.AmountIn == nil || params.AmountIn.Sign() <= 0 {
		return nil, errors.New("contract: amountIn must be positive")
	}
	if params.Deadline == nil {
		return nil, errors.New("contract: deadline is required")
	}

	// Encode the function call: function selector (first 4 bytes of keccak256
	// of the function signature) + ABI-encoded parameters.
	//
	// In real code:
	//   parsed, _ := abi.JSON(strings.NewReader(ArbitrageExecutorABI))
	//   calldata, _ := parsed.Pack("executeArbitrage", ...)
	//
	// Here we just demonstrate the concept with a simplified encoding.
	calldata := encodeExecuteArbitrage(params)

	// The "transaction" is just a descriptive struct for educational purposes.
	// A real tx would use types.NewTransaction from go-ethereum.
	hash := mockTxHash(contractAddr, nonce, calldata)

	return &SignedTx{
		Hash:     hash,
		RawHex:   "0x" + hex.EncodeToString(calldata),
		GasLimit: b.GasLimit,
		GasPrice: b.GasPrice,
		Nonce:    nonce,
	}, nil
}

// ---- Calldata encoding (educational mock) -----------------------------------

// encodeExecuteArbitrage creates a simplified ABI encoding for the arbitrage call.
// A real implementation uses github.com/ethereum/go-ethereum/accounts/abi.
func encodeExecuteArbitrage(p ArbitrageParams) []byte {
	// Function selector: first 4 bytes of keccak256("executeArbitrage(address,address,uint256,uint256,address,address,uint256)")
	// Pre-computed for this ABI:
	selector := []byte{0x12, 0x34, 0xab, 0xcd} // mock

	// In reality, each parameter is ABI-encoded (32 bytes per slot):
	// - addresses are left-padded to 32 bytes
	// - uint256 is big-endian 32 bytes
	var params []byte
	params = append(params, padAddress(p.TokenIn)...)
	params = append(params, padAddress(p.TokenOut)...)
	params = append(params, padUint256(p.AmountIn)...)
	params = append(params, padUint256(p.AmountOutMin)...)
	params = append(params, padAddress(p.PoolBuy)...)
	params = append(params, padAddress(p.PoolSell)...)
	params = append(params, padUint256(p.Deadline)...)

	return append(selector, params...)
}

func padAddress(addr string) []byte {
	addr = strings.TrimPrefix(addr, "0x")
	b, _ := hex.DecodeString(fmt.Sprintf("%040s", addr))
	padded := make([]byte, 32)
	copy(padded[12:], b)
	return padded
}

func padUint256(n *big.Int) []byte {
	if n == nil {
		return make([]byte, 32)
	}
	b := n.Bytes()
	padded := make([]byte, 32)
	copy(padded[32-len(b):], b)
	return padded
}

func mockTxHash(to string, nonce uint64, data []byte) string {
	// In production: keccak256(RLP(nonce, gasPrice, gasLimit, to, value, data, v, r, s))
	return fmt.Sprintf("0xmock_%s_%d_%x", to[:min(6, len(to))], nonce, data[:min(4, len(data))])
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// ---- Gas estimation ---------------------------------------------------------

// EstimateGas returns a gas estimate for a given operation type.
// In production: call eth_estimateGas on the RPC endpoint.
//
// Typical gas costs (Ethereum mainnet, mid-2024):
//   - ERC-20 transfer:    ~65,000 gas
//   - Uniswap V2 swap:    ~120,000 gas
//   - Uniswap V3 swap:    ~150,000 gas
//   - 2-hop arbitrage:    ~250,000 – 350,000 gas
//   - Flash loan arb:     ~400,000 – 600,000 gas
func EstimateGas(opType string) uint64 {
	switch opType {
	case "erc20_transfer":
		return 65_000
	case "uniswap_v2_swap":
		return 120_000
	case "uniswap_v3_swap":
		return 150_000
	case "two_hop_arb":
		return 280_000
	case "flash_loan_arb":
		return 500_000
	default:
		return 300_000
	}
}

// ---- MEV context (educational) ----------------------------------------------

// MEVContext explains the MEV environment that affects arbitrage execution.
// This is not executable code – it's a structured explanation of the concepts
// that every on-chain arbitrageur must understand.
type MEVContext struct {
	// MempoolVisibility: your transaction is visible to everyone before inclusion.
	// Bots scan the mempool and can "sandwich" your tx:
	//   1. Frontrun:  bot places tx BEFORE yours, buying the token at lower price
	//   2. Your tx:   price moves against you, you pay more
	//   3. Backrun:   bot places tx AFTER yours, selling what it bought at profit
	//
	// Mitigation: use Flashbots MEV-Boost to submit private bundle directly to builders.
	MempoolVisibility string

	// BlockTime is 12 seconds on Ethereum. Your tx must be included in the NEXT block.
	// If the opportunity disappears before block N+1, your tx reverts.
	BlockTime string

	// GasPriceAuction: to get included, your gas price must be high enough.
	// In competitive arb, bots bid gas up to 99% of the profit.
	// Example: $50 arb → bots bid ~$49 in gas → only $1 left for you.
	// This is why small opportunities are unprofitable.
	GasPriceAuction string

	// PrivateMempool: services like Flashbots, Eden, BloXroute allow private tx submission.
	// Your tx is invisible in the public mempool, protecting from sandwich attacks.
	PrivateMempool string
}

// NewMEVContext returns a populated MEVContext for educational display.
func NewMEVContext() MEVContext {
	return MEVContext{
		MempoolVisibility: "All pending transactions are visible. Bots scan 24/7.",
		BlockTime:         "~12 seconds on Ethereum. Your window to capture an opportunity.",
		GasPriceAuction:   "Gas price = bid for block space. Competitive arb = nearly all profit spent on gas.",
		PrivateMempool:    "Flashbots RPC: submit bundles privately to prevent sandwich attacks.",
	}
}

// FromOpportunity converts a detected arbitrage opportunity to contract parameters.
func FromOpportunity(opp types.ArbitrageOpportunity, cfg types.Config) (ArbitrageParams, error) {
	if len(opp.Route) < 2 {
		return ArbitrageParams{}, errors.New("contract: need at least 2 hops for arbitrage")
	}

	buyHop  := opp.Route[0]
	sellHop := opp.Route[1]

	amountIn  := opp.TokenIn.ToRaw(opp.InputAmount)
	// Set minimum output to 99% of expected (1% slippage protection)
	minOut    := opp.TokenIn.ToRaw(opp.OutputAmount * 0.99)
	deadline  := big.NewInt(9_999_999_999) // far future for testnet demos

	return ArbitrageParams{
		TokenIn:      buyHop.TokenIn.Address,
		TokenOut:     buyHop.TokenOut.Address,
		AmountIn:     amountIn,
		AmountOutMin: minOut,
		PoolBuy:      buyHop.Pool.Address,
		PoolSell:     sellHop.Pool.Address,
		Deadline:     deadline,
	}, nil
}
